apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
spec:
  template:
    spec:
      containers:
        - name: django-app
          image: regiapriandi012/bismillah-final-deploykube:latest
          command: ["/bin/sh","-c"]
          args: ["python manage.py makemigrations djangoBlogAmpApp && python manage.py migrate"]
          env:
            - name: DATABASE_USER
              value: "regiapriandi"
            - name: DATABASE_PASSWORD
              value: "postgres"
            - name: DATABASE_HOST
              value: "db"
            - name: DATABASE_NAME
              value: "postgres"
      restartPolicy: Never
  backoffLimit: 5

